- 👋 Hi, I’m @Mirusenpai
- 👀 I’m interested in digital marketing and crypto.
- 🌱 I’m currently learning social media marketing and crypto investing.
- 💞️ I’m looking to collaborate with people with more of a tech background.
- 📫 How to reach me: here or on ig: miranda_chau.
